feat: New SHOP added
* fix: guard remake, now works fine

* feat: SHOP first version completed
feat: refactor all to footer
feat: take damage numbers update on your damage
feat: coin management on playerService
fix: correction on go_home button
fix: health increase on birds refactor to BirdService

ERROR: Need to make coins update on click per bird, instead of per match